package nl.rug.oop.rts.model;

/**
 * enum for the army types.
 */
public enum ArmyType {
    ARRYN_ARCHER,
    ARRYN_SOLDIER,
    BARATHEON_ARCHER,
    BARATHEON_FIGHTER,
    DOTHRAKI_ARCHER,
    DOTHRAKI_RIDER,
    DRAGON,
    FACELESS_MAN,
    FREE_FOLK_ARCHER,
    FREE_FOLK_WARRIOR,
    GREYJOY_ARCHER,
    GREYJOY_SOLDIER,
    KINGS_GUARD,
    LANNISTER_SOLDIER,
    LANNISTER_ARCHER,
    MARTELL_FIGHTER,
    MARTELL_SPEARMAN,
    STARK_ARCHER,
    STARK_SOLDIER,
    TYRELL_ARCHER,
    TYRELL_SOLDIER,
    UNSULLIED
}
